---
title: "Project 1"
author: "Alexis Hernandez"
date: "2019-12-16"
output: 
  html_document: default
  pdf_document: default
---



<div id="alexis-hernandez-ash2829" class="section level2">
<h2>Alexis Hernandez ash2829</h2>
<div id="introduction" class="section level3">
<h3>0. Introduction</h3>
<p><em>The datasets I have chosen are named <code>fifa_audience</code> and <code>drinks</code> which contain data representing information on a FIFA audience sample and alcohol servings in different countries, respectively. The first dataset contains detailed data on how wide an audience the World Cup reached on television in different countries. The variables include the FIFA viewers country, the confederation of the country, the country’s share of the global population, the country’s share of the World Cup’s television audience, and the country’s GDP-weighted audience share. The second dataset contains data on average alcohol consumption per capita for those age 15 and over in different countries and describes consumption by beverage type. The variables include the country, servings of beer, servings of spirits, servings of wine, and total liters of pure alcohol per person. These were both obtained from the <code>fivethirtyeight</code> package which I found particularly interesting because the datasets in this package have their own articles that discuss the data’s relevance in a real-world context. Furthermore, the datasets were interesting in themselves because not only is soccer the most popular sport in the world, but I am also a fan and support a few teams myself. Seeing as sports are typically associated with alcohol consumption, I figured it would be engaging to study their possible relationship based on country. With that, I expect there to be a positive relationship with FIFA viewers in wealthier countries and the average alcohol consumption per capita in those same countries.</em></p>
</div>
<div id="tidying-rearranging-widelong" class="section level3">
<h3>1. Tidying: Rearranging Wide/Long</h3>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ───────────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ tibble  2.1.3     ✓ dplyr   0.8.3
## ✓ tidyr   1.0.0     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.4.0
## ✓ purrr   0.3.3</code></pre>
<pre><code>## ── Conflicts ──────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>untidy_fifa &lt;- fifa_audience %&gt;% pivot_wider(names_from = &quot;country&quot;, values_from = &quot;confederation&quot;)
untidy_drinks &lt;- drinks %&gt;% pivot_wider(names_from = &quot;country&quot;, values_from = &quot;total_litres_of_pure_alcohol&quot;)
tidy_fifa &lt;- untidy_fifa %&gt;% pivot_longer(4:194, names_to=&quot;country&quot;, values_to = &quot;confederation&quot;) %&gt;% na.omit()
tidy_drinks &lt;- untidy_drinks %&gt;% pivot_longer(4:196, names_to = &quot;country&quot;, values_to = &quot;total_litres_of_pure_alcohol&quot;) %&gt;% na.omit()</code></pre>
<p><em>The two datasets <code>fifa_audience</code> and <code>drinks</code> were already tidy since the variables had their own columns and the data was presented in a long format. In order to demonstrate the use of the pivot_wider() and pivot_longer() functions, they were each made untidy and then tidy again to do so. The dataset <code>untidy-fifa</code> was created using pivot_wider() where the names came from the country variable and the values came from the confederation variable. This reshaped the data from long to wide as each country now had its own column and its values consisted of a corresponding confederation. The same function was applied to the ‘drinks’ dataset but here the names came from the country variable and the values came from the total_litres_of_pure_alcohol variable. The dataset was named <code>untidy_drinks</code> with each country having its own column and its values consisting of a corresponding liter of alcohol. The datasets were made tidy again using pivot_longer() where the column range was specified and names_to and values_to were used. This essentially did the reverse of the pivot_wider() function as the untidy datasets were reshaped from wide to long. For each untidy dataset, each country column went into a single column named country and the corresponding values went into their own columns as well. These were named confederation and total_litres_of_pure_alcohol, respectively. In order to have clean tidy data, the na.omit() function was also used to remove the NA’s from <code>tidy_fifa</code> and <code>tidy_drinks</code> which were generated from making the untidy datasets.</em></p>
</div>
<div id="joiningmerging" class="section level3">
<h3>2. Joining/Merging</h3>
<pre class="r"><code>fifa_drinks &lt;- left_join(fifa_audience, drinks)</code></pre>
<pre><code>## Joining, by = &quot;country&quot;</code></pre>
<p><em>The datasets were joined using the left_join() function where all the rows from <code>fifa_audience</code> were kept and the rows with matches from <code>drinks</code> were added. This meant that they were joined by country. The rows in <code>fifa_audience</code> that did not have a match in <code>drinks</code> had NAs in the new columns. This meant that the countries that did not have a match now had NAs in the added columns from <code>drinks</code>. This join was used because it was necessary for all the countries in <code>fifa_audience</code> to be kept for the purpose of the study. The countries in <code>drinks</code> were needed to match them in order to give the study more context. The joined dataset was named <code>fifa_drinks</code>.</em></p>
</div>
<div id="wrangling" class="section level3">
<h3>3. Wrangling</h3>
<pre class="r"><code>fifa_drinks %&gt;% filter(confederation == &quot;CONMEBOL&quot;) %&gt;% arrange(desc(gdp_weighted_share)) %&gt;% select(country, gdp_weighted_share,tv_audience_share, total_litres_of_pure_alcohol) %&gt;% mutate(dec_gdp = gdp_weighted_share/100, dec_tv_audience = tv_audience_share/100)</code></pre>
<pre><code>## # A tibble: 10 x 6
##    country gdp_weighted_sh… tv_audience_sha… total_litres_of… dec_gdp
##    &lt;chr&gt;              &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;   &lt;dbl&gt;
##  1 Brazil               5.4              7.1              7.2   0.054
##  2 Argent…              1.6              1.5              8.3   0.016
##  3 Colomb…              0.9              1.6              4.2   0.009
##  4 Venezu…              0.9              1                7.7   0.009
##  5 Chile                0.6              0.6              7.6   0.006
##  6 Peru                 0.4              0.8              6.1   0.004
##  7 Ecuador              0.3              0.5              4.2   0.003
##  8 Uruguay              0.1              0.1              6.6   0.001
##  9 Paragu…              0.1              0.2              7.3   0.001
## 10 Bolivia              0                0.1              3.8   0    
## # … with 1 more variable: dec_tv_audience &lt;dbl&gt;</code></pre>
<pre class="r"><code>fifa_drinks %&gt;% group_by(confederation) %&gt;% na.omit() %&gt;% summarize(mean(total_litres_of_pure_alcohol), sd(total_litres_of_pure_alcohol), min(total_litres_of_pure_alcohol), max(total_litres_of_pure_alcohol), n())</code></pre>
<pre><code>## # A tibble: 6 x 6
##   confederation `mean(total_lit… `sd(total_litre… `min(total_litr…
##   &lt;chr&gt;                    &lt;dbl&gt;            &lt;dbl&gt;            &lt;dbl&gt;
## 1 AFC                       2.15             2.74              0  
## 2 CAF                       3.06             2.80              0  
## 3 CONCACAF                  5.71             2.54              2.2
## 4 CONMEBOL                  6.3              1.66              3.8
## 5 OFC                       3.58             3.07              0.9
## 6 UEFA                      8.52             3.12              1.3
## # … with 2 more variables: `max(total_litres_of_pure_alcohol)` &lt;dbl&gt;,
## #   `n()` &lt;int&gt;</code></pre>
<pre class="r"><code>fifa_drinks %&gt;% na.omit() %&gt;% summarize(mean(beer_servings), sd(beer_servings), min(beer_servings), max(beer_servings), n())</code></pre>
<pre><code>## # A tibble: 1 x 5
##   `mean(beer_servin… `sd(beer_serving… `min(beer_servin… `max(beer_servin… `n()`
##                &lt;dbl&gt;             &lt;dbl&gt;             &lt;int&gt;             &lt;int&gt; &lt;int&gt;
## 1               107.              102.                 0               376   168</code></pre>
<pre class="r"><code>fifa_drinks %&gt;% na.omit() %&gt;% group_by(tv_audience_share) %&gt;% summarize(mean_total=mean(total_litres_of_pure_alcohol), mean_gdp=mean(gdp_weighted_share)) %&gt;% cor()</code></pre>
<pre><code>##                   tv_audience_share  mean_total  mean_gdp
## tv_audience_share        1.00000000 -0.09281322 0.7382969
## mean_total              -0.09281322  1.00000000 0.2499638
## mean_gdp                 0.73829692  0.24996382 1.0000000</code></pre>
<p><em>The six core dpylr functions were used to manipulate and explore the dataset. First, the filter() function was used to choose the rows that had CONMEBOL as their confederation. The arrange() function was piped next to sort the gdp_weighted_share values from greatest to least using the desc() function. The select() function was piped next to choose the country, gdp_weighted_share, tv_audience_share, and total_litres_of_pure_alcohol variables. The mutate() function was piped next to create two new variables where the gdp_weighted_share and tv_audience_share variables were divided by 100 to turn their percentage values into decimals. These were called dec_gdp and dec_tv_audience, respectively. The output gave 10 rows because there were 10 countries in the CONMEBOL confederation, each with their corresponding values for GDP, FIFA tv audience, total liters of alcohol, and the decimal values for the GDP and tv audience percentages.</em>
<em>Summary statistics were also created to display the mean, standard deviation, minimum, maximum, and count values of the total_litres_of_pure_alcohol variable. The group_by() function was used to create a subset of the data where confederation was the variable being grouped by. The summarize() function was piped after to find the mean, standard deviation (sd), minimum (min), maximum (max), and count (n) values of total liters of alcohol for each confederation. The na.omit() function was also used to remove the NAs from the dataset before the calculations were performed. The output displayed the mentioned summary statistics for each confederation. Another summarize() function was used to find the mean, standard deviation, minimum, maximum, and count values of the beer_servings variable after removing NAs. According to the output, the mean beer servings was 107.47, the standard deviation was 101.65, the minimum was 0, the maximum was 376, and the count was 168 which corresponds to the total number of countries without NA values. In another code, group_by() was used to group by the tv_audience_share variable after the NAs were removed from the dataset. The summarize() function was piped after to find the mean of total_litres_of_pure_alcohol and the mean of gdp_weighted_shares. This was then piped into the cor() function to display the correlations between the summary statistics. According to the output, mean GDP and mean TV audience share had the highest correlation.</em></p>
</div>
<div id="visualizing" class="section level3">
<h3>4. Visualizing</h3>
<pre class="r"><code>fifa_drinks1 &lt;- fifa_drinks %&gt;% na.omit()
ggplot(fifa_drinks1, aes(tv_audience_share, total_litres_of_pure_alcohol, color = confederation))+geom_point()+ggtitle(&quot;Relationship between FIFA TV audience share and total liters of alcohol per confederation&quot;)+xlab(&quot;Percentage of country&#39;s FIFA TV audience share&quot;)+ylab(&quot;Total liters of alcohol&quot;)</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>fifa_drinks1 %&gt;% mutate(total_alcohol_tertile=ntile(total_litres_of_pure_alcohol,3)) %&gt;% ggplot(aes(x = total_alcohol_tertile, y = tv_audience_share, fill=confederation))+ geom_bar(stat=&quot;summary&quot;,fun.y=&quot;mean&quot;, position=&quot;dodge&quot;)+
geom_errorbar(stat=&quot;summary&quot;,position=&quot;dodge&quot;)+ggtitle(&quot;Tertiles of total liters of alcohol by percentage of country&#39;s FIFA TV audience share per confederation&quot;)+xlab(&quot;Tertiles of total liters of alcohol&quot;)+ylab(&quot;Percentage of country&#39;s FIFA TV audience share&quot;)</code></pre>
<pre><code>## No summary function supplied, defaulting to `mean_se()</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<p><em>The plot named “Relationship between FIFA TV audience and total liters of alcohol per confederation” illustrates the relationship between the confederation, tv_audience_share, and total_litres_of_pure_alcohol variables. According to the plot, most countries in the UEFA confederation consume the most alcohol and lie between 0 and 3 for TV audience share. Most of the countries in the CONCACAF, CONMEBOL, and OFC confederations drink an intermediate amount of alcohol and lie between 0 and 4 for TV audience share. Most of the countries in the CAF and AFC confederations drink the least amount of alcohol and lie mainly between 0 and 1 for TV audience share. There are a few countries in each confederation that make up a higher TV audience share than the majority of the countries in their confederations. There is one country in the AFC confederation that acts as an extreme outlier in the plot because its TV audience share lies just under 15. The next highest country for tv audience share is in the CONMEBOL confederation and lies at about 7 which is a big difference from the outlier. Excluding the outlier, the countries that have a higher tv audience share drink an intermediate amount of alcohol and the countries behind them range between low and high for total amount of alcohol consumed.</em>
<em>The bar chart named “Tertiles of total liters of alcohol by percentage of country’s FIFA TV audience share per confederation” maps the total_alcohol_tertile, tv_audience_share, and confederation variables to display how spread the data are around the mean value, the reliability of the mean value, and the likelihood of there being a significant difference between the variables. A smaller standard error bar indicates a low spread meaning the data clumps around the mean, and a larger standard error bar indicates a larger spread meaning the data varies from the mean. According to the bar chart, the AFC confederation in the second and third tertiles for total liters of alcohol has the largest spread meaning the data varies from the mean for TV audience share. In the first tertile, the CONMEBOL confederation has the largest spread. For the first and second tertiles, the CAF and OFC confederations have the lowest spreads meaning the data does not vary from the mean for TV audience share. In the third tertile, the OFC and CONCACAF confederations have the lowest spreads. The reliability of the mean value can also be indicated by the standard error bars with a smaller bar meaning the mean is more reliable and a larger bar meaning the mean is less reliable. For instance in the third tertile, the CONCAFAC and OFC confederation means are more reliable than the AFC and CONMEBOL means because they have shorter bars. In the first and second tertiles, the CAF and OFC confederations have shorter bars indicating that their means are also more reliable. Lastly, when the bars overlap the difference between the variables is not statistically significant. In contrast, when the bars do not overlap the difference may be significant. For instance in the third tertile, the difference between the total liters of alcohol and TV audience share is not significant for the AFC and CONMEBOL confederations. However, in the second tertile the difference is significant for the CAF and CONCACAF confederations.</em></p>
</div>
<div id="dimensionality-reduction" class="section level3">
<h3>5. Dimensionality Reduction</h3>
<pre class="r"><code>fifa_nums &lt;- fifa_drinks %&gt;% select_if(is.numeric)%&gt;%mutate_all(function(x)log(x+1)) %&gt;% scale %&gt;% na.omit()
fifa_pca&lt;-princomp(fifa_nums)
names(fifa_pca)</code></pre>
<pre><code>## [1] &quot;sdev&quot;     &quot;loadings&quot; &quot;center&quot;   &quot;scale&quot;    &quot;n.obs&quot;    &quot;scores&quot;   &quot;call&quot;</code></pre>
<pre class="r"><code>summary(fifa_pca, loadings=T)</code></pre>
<pre><code>## Importance of components:
##                           Comp.1    Comp.2     Comp.3     Comp.4     Comp.5
## Standard deviation     1.8033191 1.5381934 0.68776027 0.58639623 0.51635497
## Proportion of Variance 0.4723118 0.3436415 0.06870018 0.04994201 0.03872402
## Cumulative Proportion  0.4723118 0.8159533 0.88465349 0.93459550 0.97331952
##                            Comp.6      Comp.7
## Standard deviation     0.36846224 0.218942786
## Proportion of Variance 0.01971831 0.006962176
## Cumulative Proportion  0.99303782 1.000000000
## 
## Loadings:
##                              Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7
## population_share                     0.584  0.273  0.168  0.687         0.275
## tv_audience_share             0.228  0.578               -0.197        -0.754
## gdp_weighted_share            0.286  0.467 -0.300 -0.231 -0.464 -0.111  0.574
## beer_servings                 0.476 -0.163         0.661 -0.151  0.521  0.118
## spirit_servings               0.438 -0.129  0.719 -0.476 -0.120  0.183       
## wine_servings                 0.439 -0.198 -0.557 -0.428  0.475  0.199       
## total_litres_of_pure_alcohol  0.502 -0.158         0.265  0.105 -0.797</code></pre>
<pre class="r"><code>eigval&lt;-fifa_pca$sdev^2
varprop=round(eigval/sum(eigval),2)
ggplot()+geom_bar(aes(y=varprop,x=1:7),stat=&quot;identity&quot;)+xlab(&quot;&quot;)+geom_path(aes(y=varprop,x=1:7))+ geom_text(aes(x=1:7,y=varprop,label=round(varprop,2)),vjust=1,col=&quot;white&quot;,size=5)+ scale_y_continuous(breaks=seq(0,.6,.2),labels = scales::percent)+ scale_x_continuous(breaks=1:10)</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<pre class="r"><code>round(cumsum(eigval)/sum(eigval),2)</code></pre>
<pre><code>## Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7 
##   0.47   0.82   0.88   0.93   0.97   0.99   1.00</code></pre>
<pre class="r"><code>eigval</code></pre>
<pre><code>##     Comp.1     Comp.2     Comp.3     Comp.4     Comp.5     Comp.6     Comp.7 
## 3.25195970 2.36603883 0.47301419 0.34386053 0.26662246 0.13576442 0.04793594</code></pre>
<pre class="r"><code>summary(fifa_pca, loadings=T)</code></pre>
<pre><code>## Importance of components:
##                           Comp.1    Comp.2     Comp.3     Comp.4     Comp.5
## Standard deviation     1.8033191 1.5381934 0.68776027 0.58639623 0.51635497
## Proportion of Variance 0.4723118 0.3436415 0.06870018 0.04994201 0.03872402
## Cumulative Proportion  0.4723118 0.8159533 0.88465349 0.93459550 0.97331952
##                            Comp.6      Comp.7
## Standard deviation     0.36846224 0.218942786
## Proportion of Variance 0.01971831 0.006962176
## Cumulative Proportion  0.99303782 1.000000000
## 
## Loadings:
##                              Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7
## population_share                     0.584  0.273  0.168  0.687         0.275
## tv_audience_share             0.228  0.578               -0.197        -0.754
## gdp_weighted_share            0.286  0.467 -0.300 -0.231 -0.464 -0.111  0.574
## beer_servings                 0.476 -0.163         0.661 -0.151  0.521  0.118
## spirit_servings               0.438 -0.129  0.719 -0.476 -0.120  0.183       
## wine_servings                 0.439 -0.198 -0.557 -0.428  0.475  0.199       
## total_litres_of_pure_alcohol  0.502 -0.158         0.265  0.105 -0.797</code></pre>
<pre class="r"><code>eigen(cor(fifa_nums))</code></pre>
<pre><code>## eigen() decomposition
## $values
## [1] 3.29422765 2.42003666 0.47944032 0.34746925 0.27275223 0.13670648 0.04936741
## 
## $vectors
##            [,1]       [,2]        [,3]        [,4]        [,5]        [,6]
## [1,] -0.0757550  0.5741672 -0.29280658  0.18925854  0.67751018 -0.06672938
## [2,] -0.2430830  0.5625845  0.04865514  0.02608354 -0.17743237 -0.06075657
## [3,] -0.3117187  0.4723718  0.31333858 -0.24178879 -0.45223198  0.10789138
## [4,] -0.4690072 -0.1808471  0.03054623  0.65722125 -0.17129200 -0.51999615
## [5,] -0.4320634 -0.1461514 -0.70870985 -0.49258970 -0.11505940 -0.18363925
## [6,] -0.4315327 -0.2125294  0.55297345 -0.39959641  0.50400586 -0.19847887
## [7,] -0.4951124 -0.1773724 -0.06880087  0.26604016  0.09155557  0.79793612
##              [,7]
## [1,]  0.282074268
## [2,] -0.765629198
## [3,]  0.553984742
## [4,]  0.121312959
## [5,]  0.009203475
## [6,] -0.098681489
## [7,] -0.052984615</code></pre>
<pre class="r"><code>pca_df&lt;-fifa_drinks%&gt;%na.omit%&gt;%mutate(PC1=fifa_pca$scores[,1],PC2=fifa_pca$scores[,2])
pca_df%&gt;%
ggplot(aes(PC1,PC2,color=confederation))+geom_point()</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-5-2.png" width="672" /></p>
<p><em>A principal component analysis (PCA) was performed in in order to convert correlated variables into uncorrelated variables or principal components. First, the dataset <code>fifa_nums</code> was created using the select.if() function to choose only the numeric variables from the original dataset. The values for each variable were scaled and the NAs were also removed. A principal component analysis was performed on the scaled numeric data using princomp() to create <code>fifa_pca</code>. The results in the new dataset were summarized with loadings to give the summary statistics of standard deviation, proportion of variance, and cumulative proportion for the components. The output displayed the correlation between the numeric variables in each component. In order to decide which principal components (PCs) to keep, the proportion of variance explained by each PC was plotted in order to do so. The eigenvalues were calculated by squaring the standard deviations which were needed to determine the proportion of variance explained by each PC (varprop). PC1 and PC2 were kept because they were both before the elbow on the plot, their cumulative proportion of variance was less than 80%, and their eiganvalues were greater than 1. In order to interpret these two components, the loadings and eigenvector part of the summary statistics was analyzed. In PC1, the loadings had similar signs and magnitude and indicated that the countries who scored higher (less negative) on their tv audience and weighted GDP shares scored lower (more negative) on the servings of different types of alcoholic drinks per person and even lower on the total liters of alcohol consumed per person. Since all the scores were negative, the higher a country scored on PC1, the stronger overall. In PC2, countries who scored low on their global population, TV audience, and weighted GDP shares scored high on the servings of different types of alcoholic drinks per person and total liters of alcohol consumed per person. Lastly, the scores were plotted using ggplot() to display the data with respect to PC1 and PC2. The relationship between confederation and the numeric variables in the first two PCs was illustrated in the plot. According to the plot, most countries in any of the six confederations scored relatively high on PC2 however, they each range on their scores on PC1. For instance, most countries in the AFC and CAF confederations scored high on PC1, most countries in the OFC, CONCACAF, and CONMEBOL confederations scored in the middle range on PC1, and most countries in the UEFA confederations scored low on PC1.</em></p>
<p>Note that the <code>echo = FALSE</code> parameter was added to the code chunk to prevent printing of the R code that generated the plot.</p>
</div>
</div>
