---
title: "Project 2"
author: "Alexis Hernandez"
date: "11/24/2019"
output:
  html_document: default
  pdf_document: default
---



<div id="alexis-hernandez-ash2829" class="section level2">
<h2>Alexis Hernandez (ash2829)</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
<div id="section" class="section level3">
<h3>0.</h3>
<p><em>The dataset of interest is named <code>stagec</code> and contains data representing information on stage C prostate cancer in order to explore the prognostic values of flow cytometry. The dataset contains 146 observations (information for 146 patients) on 8 variables and was obtained from the <code>rpart</code> package. The variables for the dataset include pgtime, pgstat, age, eet, g2, grade, gleason, and ploidy. Pgtime is a numerical variable and comprises the time to progression or last follow-up in years. Pgstat is a categorical variable with two levels, progession observed or censored. Age is a numerical variable and comprises the ages of the patients in years. Eet is a categorical variable with two levels consisting of whether the patient recieved early endocrine therapy or not. G2 is a numerical variable and comprises the percent of cells in the G2 phase as found by flow cytometry. Grade is a categorical variable and comprises the grade of the tumor following the Farrow system. Gleason is a categorical variable and comprises the grade of the tumor following the Gleason system. Lastly, ploidy is a categorical variable describing the ploidy status of the tumor from flow cytometry.</em></p>
</div>
<div id="section-1" class="section level3">
<h3>1.</h3>
<pre class="r"><code>library(tidyverse)</code></pre>
<pre><code>## ── Attaching packages ────────────────────────────────────────────────────── tidyverse 1.3.0 ──</code></pre>
<pre><code>## ✓ ggplot2 3.2.1     ✓ purrr   0.3.3
## ✓ tibble  2.1.3     ✓ dplyr   0.8.3
## ✓ tidyr   1.0.0     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.4.0</code></pre>
<pre><code>## ── Conflicts ───────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>stagec &lt;- stagec %&gt;% na.omit()
man1&lt;-manova(cbind(g2,age,pgtime)~ploidy, data=stagec)
summary(man1)</code></pre>
<pre><code>##            Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## ploidy      2 0.48792   13.983      6    260 8.769e-14 ***
## Residuals 131                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1)</code></pre>
<pre><code>##  Response g2 :
##              Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## ploidy        2 4146.5  2073.2  53.437 &lt; 2.2e-16 ***
## Residuals   131 5082.5    38.8                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##  Response age :
##              Df Sum Sq Mean Sq F value Pr(&gt;F)
## ploidy        2   28.4  14.205  0.4147 0.6614
## Residuals   131 4487.4  34.255               
## 
##  Response pgtime :
##              Df  Sum Sq Mean Sq F value Pr(&gt;F)
## ploidy        2   44.23  22.113  1.6889 0.1887
## Residuals   131 1715.20  13.093</code></pre>
<pre class="r"><code>pairwise.t.test(stagec$g2,stagec$ploidy,p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  stagec$g2 and stagec$ploidy 
## 
##            diploid tetraploid
## tetraploid &lt; 2e-16 -         
## aneuploid  0.63    3.4e-05   
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>(1)-(0.95)^7</code></pre>
<pre><code>## [1] 0.3016627</code></pre>
<pre class="r"><code>0.05/7</code></pre>
<pre><code>## [1] 0.007142857</code></pre>
<p><em>The MANOVA tested the effect of the categorical variable, ploidy, with three levels (diploid, tetraploid, aneuploid) on three numeric variables (g2, age, and time). The probability of at least one type 1 error was 0.30 and using the bonferroni method, the adjusted significance level was 0.007.The MANOVA demonstrated that at least one of the numeric variables showed a significant mean difference across ploidy. Therefore, three univariate ANOVAs were performed to determine which of the numeric variables demonstrated a significant mean difference across the ploidy levels. The ANOVA tests demonstrated that the g2 numeric variable showed significant differences. Post-hoc analysis was performed conducting three pairwise comparisons to determine which ploidy level differed in g2. Only the tetraploid level was found to differ significantly in terms of g2 after adjusting for multiple comparisons (bonferroni). The MANOVA assumptions are random sampling/independent observations, multivariate normality of dependent variables, homogeneity of within-group covariance matrices, linear relationships among dependent variables, no extreme univariate or multivariate outliers, and no multicollinearity. All of these were likely to have been met except for the linear relationships and outliers assumptions. The linear relationships among dependent variables assumption was violated because age does not have a linear relationship with g2 or pgtime. The no extreme univariate or multivariate outliers assumption was also violated due to the presence of said outliers.</em></p>
</div>
<div id="section-2" class="section level3">
<h3>2.</h3>
<pre class="r"><code>library(vegan)</code></pre>
<pre><code>## Loading required package: permute</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre><code>## This is vegan 2.5-4</code></pre>
<pre class="r"><code>dists&lt;-vegdist(sqrt(stagec[, -c(1,3,5,8)]),method=&quot;bray&quot;)
distdiploid&lt;-vegdist(sqrt(stagec[stagec$ploidy==&quot;diploid&quot;,-c(1,3,5,8)]),method=&quot;bray&quot;)
disttetra&lt;-vegdist(sqrt(stagec[stagec$ploidy==&quot;tetraploid&quot;,-c(1,3,5,8)]),method=&quot;bray&quot;)
distaneuploid&lt;-vegdist(sqrt(stagec[stagec$ploidy==&quot;aneuploid&quot;,-c(1,3,5,8)]),method=&quot;bray&quot;)
SSR&lt;-sum(distdiploid^2)/65+sum(disttetra^2)/64+sum(distaneuploid^2/5)
SST&lt;-sum(dists^2)/134
Fstat&lt;-(SST-SSR)/(SSR/131)
Fstat</code></pre>
<pre><code>## [1] 19.77135</code></pre>
<pre class="r"><code>perm.sampdist&lt;-replicate(5000,{
new&lt;-stagec
new$ploidy&lt;-sample(stagec$ploidy)
dists&lt;-vegdist(sqrt(new[,-c(1,3,5,8)]),method=&quot;bray&quot;)
distdiploid&lt;-vegdist(sqrt(new[new$ploidy==&quot;diploid&quot;,-c(1,3,5,8)]),method=&quot;bray&quot;)
disttetra&lt;-vegdist(sqrt(new[new$ploidy==&quot;tetraploid&quot;,-c(1,3,5,8)]),method=&quot;bray&quot;)
distaneuploid&lt;-vegdist(sqrt(new[new$ploidy==&quot;aneuploid&quot;,-c(1,3,5,8)]),method=&quot;bray&quot;)
SSR&lt;-sum(distdiploid^2)/65+sum(disttetra^2)/64+sum(distaneuploid^2/5)
SST&lt;-sum(dists^2)/134
(SST-SSR)/(SSR/131)
} )
mean(perm.sampdist&gt;Fstat)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>{hist(perm.sampdist,prob = T); abline(v=Fstat, col=&quot;red&quot;, add=T)}</code></pre>
<pre><code>## Warning in int_abline(a = a, b = b, h = h, v = v, untf = untf, ...): &quot;add&quot; is
## not a graphical parameter</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p><em>The randomization test that was performed on the data was a PERMANOVA test. The null hypothesis is stated as follows: for g2, age, and pgtime, means of each ploidy level are equal. The alternative hypothesis is stated as follows: for at least one dependent variable, at least one ploidy level mean is different. After performing the PERMANOVA test, the results demonstrate that the actual F statistic is far away from the majority of the F statistics that arise in the simulationed distribution where there is no mean difference between groups. This means that there is enough evidence to indicate that g2, age, and pgtime differ between those groups. Thus, 53.44% of the simulated sampling distribution is greater than our observed F-stat. Since this distribution was created under the null hypothesis of no mean difference between groups, we have a nearly 53% chance of seeing an F-stat this large under the null, so we cannot reject this hypothesis as inconsistent with our data.</em></p>
</div>
<div id="section-3" class="section level3">
<h3>3.</h3>
<pre class="r"><code>stagec &lt;- stagec %&gt;% mutate(pgtime_c = scale(stagec$pgtime,
center = TRUE, scale = FALSE))
fit&lt;-lm(g2~ploidy*pgtime_c, data= stagec)
summary(fit)</code></pre>
<pre><code>## 
## Call:
## lm(formula = g2 ~ ploidy * pgtime_c, data = stagec)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.407 -3.762 -0.851  2.058 33.061 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                9.18207    0.77203  11.893   &lt;2e-16 ***
## ploidytetraploid          11.00523    1.09497  10.051   &lt;2e-16 ***
## ploidyaneuploid           -2.49311    3.83190  -0.651    0.516    
## pgtime_c                  -0.05906    0.24298  -0.243    0.808    
## ploidytetraploid:pgtime_c  0.42324    0.31176   1.358    0.177    
## ploidyaneuploid:pgtime_c  -0.31663    0.90860  -0.348    0.728    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.212 on 128 degrees of freedom
## Multiple R-squared:  0.4648, Adjusted R-squared:  0.4439 
## F-statistic: 22.24 on 5 and 128 DF,  p-value: 5.416e-16</code></pre>
<pre class="r"><code>newdat&lt;-stagec
newdat$ploidy&lt;-rep(&quot;diploid&quot;,length(newdat$ploidy))
newdat$pred1&lt;-predict(fit,newdat)
newdat$ploidy&lt;-rep(&quot;tetraploid&quot;,length(newdat$ploidy))
newdat$pred2&lt;-predict(fit,newdat)
newdat$ploidy&lt;-rep(&quot;aneuploid&quot;,length(newdat$ploidy))
newdat$pred3&lt;-predict(fit,newdat)
ggplot(stagec, aes(x = pgtime_c, y = g2)) + geom_point() + geom_line(data = newdat, aes(y = pred1),color=&#39;blue&#39; ) + geom_line(data = newdat, aes(y = pred2),color=&#39;red&#39; ) + geom_line(data = newdat, aes(y = pred3),color=&#39;green&#39; )</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>resids&lt;-fit$residuals 
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids), bins=20)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
<pre class="r"><code>shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.78141, p-value = 7.426e-13</code></pre>
<pre class="r"><code>library(sandwich)
library(lmtest)</code></pre>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre class="r"><code>bptest(fit) </code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 9.4469, df = 5, p-value = 0.09251</code></pre>
<pre class="r"><code>summary(fit)$coef[,1:2]</code></pre>
<pre><code>##                              Estimate Std. Error
## (Intercept)                9.18207048  0.7720314
## ploidytetraploid          11.00522807  1.0949668
## ploidyaneuploid           -2.49310964  3.8318963
## pgtime_c                  -0.05905771  0.2429833
## ploidytetraploid:pgtime_c  0.42323946  0.3117609
## ploidyaneuploid:pgtime_c  -0.31662763  0.9085955</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))[,1:2]</code></pre>
<pre><code>##                              Estimate Std. Error
## (Intercept)                9.18207048  0.3287006
## ploidytetraploid          11.00522807  1.1234610
## ploidyaneuploid           -2.49310964  8.5497955
## pgtime_c                  -0.05905771  0.1281764
## ploidytetraploid:pgtime_c  0.42323946  0.2816146
## ploidyaneuploid:pgtime_c  -0.31662763  1.9230183</code></pre>
<pre class="r"><code>(sum((stagec$g2-mean(stagec$g2))^2)-sum(fit$residuals^2))/sum((stagec$g2-mean(stagec$g2))^2)</code></pre>
<pre><code>## [1] 0.4648385</code></pre>
<p><em>A linear regression model was performed to predict g2 from the interaction of ploidy level and pgtime_c. The full model with the interaction is g2 = 9.18 + 11.01(ploidytetraploid) - 2.49(ploidyaneuploid) - 0.06(pgtime_c) + 0.42(ploidytetraploid:pgtime_c) - 0.32(ploidyaneuploid:pgtime_c). Controlling for pgtime_c, when ploidytetraploid is 1 and the other ploidy levels are 0, g2 increases by a factor of 11.01. Controlling for pgtime_c, when ploidyaneuploid is 1 and the other ploidy levels are 0, g2 decreases by a factor of 2.49. For every 1-unit increase in pgtime_c, g2 decreases by a factor of 0.06 on average. For the interaction, when ploidytetraploid is 1 and the other ploidy levels are 0, the resulting equation is g2 = 20.19 + 0.36(pgtime_c). For the interaction, when ploidyaneuploid is 1 and the other ploidy levels are 0, the resulting equation is g2 = 6.69 - 0.38(pgtime_c). The estimate for the interaction term is the difference in the slopes. After checking the assumptions, the data was heteroskedastic so robust standard errors for the regression results were computed. This was performed to correct the standard errors since the data was heteroskedastic, rather than homoskedastic. The significance of the results showed that there was a change from the uncorrected SEs to the corrected SEs (robust SEs), indicating that the data did violate the homoskedastic assumption. The uncorrected SEs for the predictors generally increased in value after correcting by computing for robust SEs. The uncorrected SEs for the interactions either increased or decreased in value after correcting by computing for robust SEs. The proportion of variation in the response variable (g2) is 0.4648 and is explained by the overall model. </em></p>
</div>
<div id="section-4" class="section level3">
<h3>4.</h3>
<pre class="r"><code>bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 9.4469, df = 5, p-value = 0.09251</code></pre>
<pre class="r"><code>x=seq(-5,5,length.out=1000)
y=1+2*x+rnorm(1000)
dat&lt;-data.frame(x,y)
boot_dat&lt;-dat[sample(nrow(dat),replace=TRUE),]
samp_distn&lt;-replicate(5000, {
 boot_dat&lt;-stagec[sample(nrow(stagec),replace=TRUE),]
 fit&lt;-lm(g2~ploidy*pgtime_c,data=boot_dat)
 coef(fit)
})
do.call(rbind,lapply(samp_distn,unlist))%&gt;%as.data.frame%&gt;%summarize_all(sd,na.rm=T)</code></pre>
<pre><code>## Warning in (function (..., deparse.level = 1) : number of columns of result is
## not a multiple of vector length (arg 485)</code></pre>
<pre><code>##   (Intercept) ploidytetraploid ploidyaneuploid  pgtime_c
## 1    0.320971         1.095673        10.63158 0.1284689
##   ploidytetraploid:pgtime_c ploidyaneuploid:pgtime_c
## 1                 0.7106842                 2.832238</code></pre>
<p><em>The regression model with the interaction was used to compute bootstrapped SEs to observe and compare them to the orignial SEs and the robust SEs. Compared to the original SEs, the bootstrapped SEs were generally very different in value. Compared to the robust SEs, the bootstrapped SEs were generally very similar in value, in fact, the SE values are almost the same. However, the bootstrapped SEs for ploidyaneuploid and both of the interactions were slightly larger than the robust SEs. The p-value for the interaction model was 0.09.</em></p>
</div>
<div id="section-5" class="section level3">
<h3>5.</h3>
<pre class="r"><code>fit1&lt;-glm(pgstat~ ploidy + g2 ,data=stagec,family=&quot;binomial&quot;)
coeftest(fit1)</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                   Estimate Std. Error z value  Pr(&gt;|z|)    
## (Intercept)      -0.980271   0.422074 -2.3225 0.0202057 *  
## ploidytetraploid  1.874567   0.525498  3.5672 0.0003608 ***
## ploidyaneuploid   2.722118   1.163060  2.3405 0.0192590 *  
## g2               -0.044690   0.031774 -1.4065 0.1595802    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit1))</code></pre>
<pre><code>##      (Intercept) ploidytetraploid  ploidyaneuploid               g2 
##        0.3752095        6.5179971       15.2125044        0.9562942</code></pre>
<pre class="r"><code>prob&lt;-predict(fit1,type=&quot;response&quot;)
pred&lt;-ifelse(prob&gt;.5,1,0)
table(truth=stagec$pgstat,prediction=pred)%&gt;%addmargins</code></pre>
<pre><code>##      prediction
## truth   0   1 Sum
##   0    67  18  85
##   1    21  28  49
##   Sum  88  46 134</code></pre>
<pre class="r"><code>(28+67)/134 #accuracy</code></pre>
<pre><code>## [1] 0.7089552</code></pre>
<pre class="r"><code>28/49  #tpr</code></pre>
<pre><code>## [1] 0.5714286</code></pre>
<pre class="r"><code>67/85  #tnr</code></pre>
<pre><code>## [1] 0.7882353</code></pre>
<pre class="r"><code>28/46 #ppv</code></pre>
<pre><code>## [1] 0.6086957</code></pre>
<pre class="r"><code>odds&lt;-function(p)p/(1-p)
p&lt;-seq(0,1,by=.1)
cbind(p, odds=odds(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds
##  [1,] 0.0 0.0000
##  [2,] 0.1 0.1111
##  [3,] 0.2 0.2500
##  [4,] 0.3 0.4286
##  [5,] 0.4 0.6667
##  [6,] 0.5 1.0000
##  [7,] 0.6 1.5000
##  [8,] 0.7 2.3333
##  [9,] 0.8 4.0000
## [10,] 0.9 9.0000
## [11,] 1.0    Inf</code></pre>
<pre class="r"><code>logit&lt;-function(p)log(odds(p))
cbind(p, odds=odds(p),logit=logit(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds   logit
##  [1,] 0.0 0.0000    -Inf
##  [2,] 0.1 0.1111 -2.1972
##  [3,] 0.2 0.2500 -1.3863
##  [4,] 0.3 0.4286 -0.8473
##  [5,] 0.4 0.6667 -0.4055
##  [6,] 0.5 1.0000  0.0000
##  [7,] 0.6 1.5000  0.4055
##  [8,] 0.7 2.3333  0.8473
##  [9,] 0.8 4.0000  1.3863
## [10,] 0.9 9.0000  2.1972
## [11,] 1.0    Inf     Inf</code></pre>
<pre class="r"><code>stagec$logit&lt;-predict(fit1)
stagec$pgstat&lt;-factor(stagec$pgstat,levels=c(&quot;1&quot;,&quot;0&quot;))
ggplot(stagec,aes(logit, fill=pgstat))+geom_density(alpha=.3)+
  geom_vline(xintercept=0,lty=2)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>library(plotROC) 
data(stagec)%&gt;%head()</code></pre>
<pre><code>## [1] &quot;stagec&quot;</code></pre>
<pre class="r"><code>stagec &lt;- stagec %&gt;% na.omit()
fit1&lt;-glm(pgstat~g2+ploidy,data=stagec,family=&quot;binomial&quot;)
prob3&lt;-predict(fit1,type=&quot;response&quot;)
ROCplot&lt;-ggplot(stagec)+geom_roc(aes(d=pgstat,m=prob3), n.cuts=0) 
ROCplot</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.7042017</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
 tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
 acc=sum(diag(tab))/sum(tab)
 sens=tab[2,2]/colSums(tab)[2]
 spec=tab[1,1]/colSums(tab)[1]
 ppv=tab[2,2]/rowSums(tab)[2]
 if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
 ord&lt;-order(probs, decreasing=TRUE)
 probs &lt;- probs[ord]; truth &lt;- truth[ord]
 TPR=cumsum(truth)/max(1,sum(truth))
 FPR=cumsum(!truth)/max(1,sum(!truth))
 dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
 TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
 n &lt;- length(TPR)
 auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
 data.frame(acc,sens,spec,ppv,auc)
} 

set.seed(1234)
k=10 
data1&lt;-stagec[sample(nrow(stagec)),]
folds&lt;-cut(seq(1:nrow(stagec)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
 train&lt;-data1[folds!=i,]
 test&lt;-data1[folds==i,]
 truth&lt;-test$pgstat
 fit&lt;-glm(pgstat~g2+ploidy,data=train,family=&quot;binomial&quot;)
 probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
 diags&lt;-rbind(diags,class_diag(probs,truth))
}
apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.7005495 0.5961905 0.7625000 0.6100000 0.7153345</code></pre>
<p><em>A logistic regression was performed predicting the binary categorical variable, pgstat, from the explanatory variables known as g2 and ploidy. The coefficient test demonstrated that ploidytetraploid significantly increases the log-odds of progression observed (pgstat = 1). Controlling for g2, ploidyaneuploid and ploidydiploid are not signicant, whereas, ploidytetraploid and ploidydiploid are significantly different. The odds of progression observed for ploidytetraploid are 1.87 times that of diploid. Controlling for ploidy, odds of progression observed are not significantly affected by g2. A confusion matrix was performed for the logistic regresission to plot model predictions against true values. The proportion of correctly classified cases is the overall accuracy and was computed to be 0.71. The proportion of observed progressions correctly classified is the sensitivity (TPR) and was computed to be 0.57. The proportion of censored progressions (no progression observed, pgstat = 0) correctly classified is the specificity (TNR) and was computed to be 0.79. The proportion of those classified as observed progressions who actually are is the precision (PPV) and was computed to be 0.61. An ROC curve was generated to display the area under the curve (AUC) which quantifies how well the predictions are overall. The ROC plot was used to compute the AUC which was 0.704. The calculated AUC is considered fair since it lies between 0.7 and 0.8. The 10-fold CV was performed and generated an average out-of-sample accuracy value of 0.70, an average out-of-sample sensitivity value of 0.60, and an average out-of-sample recall value of 0.61.</em></p>
</div>
<div id="section-6" class="section level3">
<h3>6.</h3>
<pre class="r"><code>library(glmnet)</code></pre>
<pre><code>## Error in library(glmnet): there is no package called &#39;glmnet&#39;</code></pre>
<pre class="r"><code>fit2 &lt;- glm(pgstat ~ -1 + pgtime + age + eet + g2 + grade + gleason + ploidy, data = stagec, family = &quot;binomial&quot;)
model.matrix(fit2) %&gt;% head()</code></pre>
<pre><code>##   pgtime age eet    g2 grade gleason ploidydiploid ploidytetraploid
## 1    6.1  64   2 10.26     2       4             1                0
## 3    5.2  59   2  9.99     3       7             1                0
## 4    3.2  62   2  3.57     2       4             1                0
## 5    1.9  64   2 22.56     4       8             0                1
## 6    4.8  69   1  6.14     3       7             1                0
## 9    3.7  73   2 11.77     3       6             1                0
##   ploidyaneuploid
## 1               0
## 3               0
## 4               0
## 5               0
## 6               0
## 9               0</code></pre>
<pre class="r"><code>set.seed(1234)
x&lt;-model.matrix(fit2)
x&lt;-scale(x)
y&lt;-as.matrix(stagec$pgstat)
cv&lt;-cv.glmnet(x,y,family=&#39;binomial&#39;)</code></pre>
<pre><code>## Error in cv.glmnet(x, y, family = &quot;binomial&quot;): could not find function &quot;cv.glmnet&quot;</code></pre>
<pre class="r"><code>lasso&lt;-glmnet(x,y,family=&#39;binomial&#39;,lambda=cv$lambda.1se)</code></pre>
<pre><code>## Error in glmnet(x, y, family = &quot;binomial&quot;, lambda = cv$lambda.1se): could not find function &quot;glmnet&quot;</code></pre>
<pre class="r"><code>coef(cv)</code></pre>
<pre><code>## Error in coef(cv): object &#39;cv&#39; not found</code></pre>
<pre class="r"><code>stagec$diploid&lt;-ifelse(stagec$ploidy==&quot;diploid&quot;,1,0)
set.seed(1234)
k=10
data1&lt;-stagec[sample(nrow(stagec)),]
folds&lt;-cut(seq(1:nrow(stagec)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
 train&lt;-data1[folds!=i,]
 test&lt;-data1[folds==i,]
 truth&lt;-test$pgstat
 fit3&lt;-glm(pgstat~pgtime+grade+diploid,data=train,family=&quot;binomial&quot;)
 probs&lt;-predict(fit3,newdata = test,type=&quot;response&quot;)
 diags&lt;-rbind(diags,class_diag(probs,truth))
}
diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc     sens      spec       ppv       auc
## 1 0.8054945 0.637381 0.8835317 0.7457143 0.8989342</code></pre>
<p><em>A lasso regression was performed predicting the binary categorical variable, pgstat, with all the other variables as predictors. Lambda was chosen to give the simplest model whose accuracy is near that of the best. From the lasso, the variables that were retained were pgtime, grade, and ploidydiploid. These are the most important predictors of pgstat. After performing the 10-fold CV using this model, the out-of-sample accuracy was 0.81. The logistic regression in part 5 generated an out-of-sample accuracy value of 0.70 which was much smaller than the accuracy for this model. Therefore, the retained predictors generated a better model that makes more accurate predictions.</em></p>
<p>Note that the <code>echo = FALSE</code> parameter was added to the code chunk to prevent printing of the R code that generated the plot.</p>
</div>
</div>
